development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: foRus
  pool: 5
  username: root
  password: toor
  host: 127.0.0.1
  socket: mysql
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: foRus
  pool: 5
  username: root
  password: toor
  host: 127.0.0.1
  socket: mysql
  port: 3306