# Sample database config. Make a copy, named 'database.yml', and never push them to repository

#development:
#  database: foRus
#  username: ***
#  password: ***
  
#  adapter: mysql2
#  socket: mysql
#  port: 3306
  
#  encoding: utf8
#  reconnect: false
#  host: 127.0.0.1
#  pool: 5

#production:
#  database: foRus
#  username: ***
#  password: ***
#
#  adapter: mysql2
#  socket: mysql
#  port: 3306
#
#  encoding: utf8
#  reconnect: false
#  host: 127.0.0.1
#  pool: 5
#